CREATE TABLE CF_MEMBER(
MID  VARCHAR2(20) NOT NULL,
MPW VARCHAR2(20),
MNICKNAME VARCHAR2(20),
MNAME VARCHAR2(50),
MPHONE VARCHAR2(20),
MMAIL VARCHAR2(40),
MPOST VARCHAR2(10),
MADDRESS VARCHAR2(200),
MSADDRESS VARCHAR2(200),
CONSTRAINT CF_MEMBER_PK PRIMARY KEY(MID)
);

CREATE TABLE CF_PROJECT(
PRCODE NUMBER(10) NOT NULL,
PRNAME VARCHAR2(50),
PRDESCRIPTION  VARCHAR2(2000),
PRTEAM  VARCHAR2(500),
PRID  VARCHAR2(20),
PRCATEGORY  VARCHAR2(20),
PRGOAL  VARCHAR2(10),
PRCURRENT  VARCHAR2(20) DEFAULT 0,
PRLIKECOUNT  VARCHAR2(20) DEFAULT 0,
PRSTARTDATE  DATE DEFAULT SYSDATE,
PRENDDATE  DATE,
CONSTRAINT CF_PROJECT_PK PRIMARY KEY(PRCODE),
FOREIGN KEY(PRID) REFERENCES CF_MEMBER(MID)
);

CREATE TABLE CF_LIKELIST(
MID VARCHAR2(20) NOT NULL,
PRCODE VARCHAR2(10) NOT NULL,
FOREIGN KEY(MID) REFERENCES CF_MEMBER(MID),
FOREIGN KEY(PRCODE) REFERENCES CF_PROJECT(PRCODE)
);

CREATE TABLE CF_ANNOUNCEMENT(
ANUM number NOT NULL,
ATITLE VARCHAR2(15),
ADATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
AANNOUNCE VARCHAR2(15),
PRCODE number NOT NULL,
CONSTRAINT CF_ANNOUNCEMENT_PK PRIMARY KEY(ANUM),
FOREIGN KEY(PRCODE) REFERENCES CF_PROJECT(PRCODE)
);

CREATE TABLE CF_COMMENT(
CNUMBER VARCHAR2(15) NOT NULL,
ANUM VARCHAR(15) NOT NULL,
MID VARCHAR(20) NOT NULL, 
CCOMMENT VARCHAR2(500),
CWRITEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CUPDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE ORDER_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE orders (
    orderId INT PRIMARY KEY,
    userId VARCHAR2(20),
    prCode number NOT NULL,
    totalAmount DECIMAL(10, 2) NOT NULL,
    orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paymentId varchar(20),
    paymentStatus VARCHAR2(20),
    FOREIGN KEY (userId) REFERENCES cf_member(mId),
    FOREIGN KEY (prCode) REFERENCES cf_project(prCode)
);

CREATE TABLE payments (
    paymentId varchar(20) PRIMARY KEY,
    orderId INT,
    amount DECIMAL(10, 2) NOT NULL,
    paymentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    paymentStatus VARCHAR2(20) NOT NULL,
    FOREIGN KEY (orderId) REFERENCES orders(orderId)
);


ALTER TABLE CF_PROJECT
MODIFY (PRENDDATE TIMESTAMP );

COMMIT;